### ISSUE TITLE
Only Username/Password does not work

### ISSUE THREAD

**Issue by hypervtechnics** [Adacta/Azure-DevOps-SFTP-SSH-download#1]
If I leave the `secureFilePath` property to the default or empty it I am getting errors like
this:
```text
For the empty secureFilePath

##[error]Exception calling "Filter" with "3" argument(s): "Value cannot be null.
```

For the default I get a file not found error.

I only want to use username/password for authenticating.

**Comment by matejskubic** [comment]
Issue with file search fixed in 1.2.17 (not related with login type).

Please re-open if issue exists.
