### ISSUE TITLE
Files not being copied or not found

### ISSUE THREAD

**Issue by netdragonboberb** [Adacta/Azure-DevOps-SFTP-SSH-download#2]
Probably by the time you read this I will have already solved or used a different approach, so this is just general feedback.

Edit update: Looks like the files aren't being copied, but there's no explanation and no error.
Output var ProcessedFilesCount is 0

The SSH Connection works because I used it for running commands on the remote server in a different step.

Can you please add some additional diagnostic output of path where the files are copied, what files are copied and whether it was successful and other diagnostic info that can help us debug?

In a subsequent script task, I can't find the files anywhere in the working directory. I tried hard-coded path outputted in scripts for the working directory and also $(System.DefaultWorkingDirectory)

![image](https://user-images.githubusercontent.com/4391690/74836393-4feed380-52ed-11ea-8ae4-77b17095d511.png)

![image](https://user-images.githubusercontent.com/4391690/74836442-6eed6580-52ed-11ea-84d0-8087c63f97f1.png)

**Comment by matejskubic** [comment]
Closing issue old issues.

Please re-open if this is still actual.
