### ISSUE TITLE
Verbose Logging Output

### ISSUE THREAD

**Issue by prketner** [Adacta/Azure-DevOps-SFTP-SSH-download#8]
Is there the capability to add a flag or something within the available inputs to select whether you would like Verbose logging within the output of the ADO pipeline?

Currently there is zero logging to this task that I'm seeing

![image](https://github.com/Adacta/Azure-DevOps-SFTP-SSH-download/assets/114247085/49072ac0-5f0b-49e6-aafc-249365797981)

**Comment by matejskubic** [comment]
Please check updated version.
